### GET ALL ITEM

GET http://localhost:9000/items

### DELETE MULTIPLE

DELETE http://localhost:9000/items
Content-Type: application/json

{
  "ids": ["dc6b1edb-ac44-493d-b124-734435b1d7b3", "a7824b99-2f39-4501-8038-dc2f2742725c"]
}

### EDIT MULTIPLE

POST http://localhost:9000/items
Content-Type: application/json

{
  "items": [
    {
      "id": "dc6b1edb-ac44-493d-b124-734435b1d7b3",
      "text": "bilal",
      "done": false
    },
    {
      "id": "a7824b99-2f39-4501-8038-dc2f2742725c",
      "text": "fazlani",
      "done": false
    }
  ]
}

### CREATE ONE ITEM

PUT http://localhost:9000/item
Content-Type: application/json

{
  "text": "pqr"
}

### EDIT ONE ITEM

POST http://localhost:9000/item
Content-Type: application/json

{
  "id": "dc6b1edb-ac44-493d-b124-734435b1d7b3",
  "text": "xyz",
  "done": true
}

### DELETE ONE ITEM

DELETE http://localhost:9000/item
Content-Type: application/json

{
  "id": "21395768-f095-4e72-b888-bc5a8d268cf7"
}

### GET ONE ITEM

GET http://localhost:9000/item/dc6b1edb-ac44-493d-b124-734435b1d7b3

###